### ISSUE TITLE
Ember Global deprecation warning due to old version of ember-cli-babel in ember-cli-google-recaptcha

### ISSUE THREAD

**Issue by rahulk94** [onehilltech/ember-cli-google#4]
We're looking to upgrade our application from Ember 3.24 to 3.28 (latest LTS) and have come across the following deprecation warnings due to `ember-cli-google-recaptcha`'s use of `ember-cli-babel@6`.
```
WARNING: [DEPRECATION] [DEPRECATION] Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.

See https://deprecations.emberjs.com/v3.x/#toc_ember-global for details.

Usages of the Ember Global may be caused by an outdated ember-cli-babel dependency. The following steps may help:

* Upgrade the following addons to the latest version:
  * ember-cli-google-recaptcha
```

Is this something that could be upgraded in the package? Given a recent release was done for v3 recaptcha its probably worth getting this out soon too if possible.

Edit: v3 recaptcha === `g-recaptcha-v3` service

**Comment by hilljh82** [comment]
@rahulk94 We can look into this deprecation message. In regards to v3, we are still working on a strategy to support v3 since it behave differently to v2 and invisible.

**Comment by rahulk94** [comment]
Thanks for the super quick response @hilljh82.

Ah sorry I'm not specifically after v3 just thought I would mention since there has been recent activity on the repo so fixing deprecations whilst theres dev going on (somewhat) would be a good move.

**Comment by hilljh82** [comment]
@rahulk94 When you say v3, you mean v3 for Ember and not v3 for Google reCAPTCHA, correct?!

**Comment by rahulk94** [comment]
By v3 I meant https://github.com/onehilltech/ember-cli-google/blob/master/packages/ember-cli-google-recaptcha/addon/services/g-recaptcha-v3.js but I see now that you did that almost a year ago 😅 ...

Just after a deprecation fix here, let me know if there is something I can do to help and I'll see if I can fit in some time for it 🙂 .

**Comment by hilljh82** [comment]
Yes, I started it a while back only to realize that I needed an intuitive way to support it because of how it behaves. Some projects coming up will need v3 support, so I will be revisiting it soon. How soon, I do not know.

**Comment by rahulk94** [comment]
Sorry for mentioning the `g-recaptcha-v3` stuff earlier, somewhat derailed the original focus of this issue 😅

**Comment by hilljh82** [comment]
No worries. It's good to see that people are using this add-on. I should probably start a wiki page where people can list how they are using the add-on in the projects.

**Comment by hilljh82** [comment]
@rahulk94 I just update this add-on to build against Ember 3.24. Please let me know if this address your issue.

**Comment by rahulk94** [comment]
Oh awesome thanks @hilljh82 for the quick turnaround.
I’ll try this out on Monday and report back.

**Comment by rahulk94** [comment]
Woops so sorry @hilljh82 🤦🏾‍♂️  completely forgot about following up here.

Just checked if the deprecation warning shows up when using 2.5.0 and it does not 🙂  thanks mate.
