### ISSUE TITLE
Huge event decrease on google analytic after update to ember-cli-google-analytics@1.5.0

### ISSUE THREAD

**Issue by romgere** [onehilltech/ember-cli-google#8]
Hi there, 

I recently update to ember-cli-google-analytics@1.5.0 on one of my pet project (was previously on 1.2) & I think there's something wrong (maybe my integration) because since I got huge decrease of events on my web site : 
![image](https://github.com/onehilltech/ember-cli-google/assets/13900970/0bf553c3-5166-44b9-8b8a-dc8905a1c9ce)

Here is [gtag related changes](https://github.com/romgere/text2stl/commit/ae8d90e6bb0a658c76eaf12267027fa71bf1ff81#diff-a4c0bb9bd4c69aeae9aebaf8d48f1a137c78bd4ac2e1c901db395ccca5037cb4) : 
![image](https://github.com/onehilltech/ember-cli-google/assets/13900970/fbcd266a-0d62-433f-a281-859f66b51cd7)

Any clue on what's happening there ? Did I miss something in the changes from 1.2 to 1.5 🤔 

Thanks !

**Comment by hilljh82** [comment]
@romgere Are you using V4 via the Tag Manager?

**Comment by romgere** [comment]
@hilljh82 I won't lie I'm not sure, I can't find any "version" indicator in Google Analytics / Tag manager... I created the tag 1 year ago, so I was assuming that it's a v4 🤷🏻‍♂️ 

I was using version 1.2 with v4 config & didn't change it when upgrade to 1.5 : 
```
'ember-cli-google': {
      analytics: {
        version: 'v4',
        measurementId: 'G-47QBQ5GB3Y',
      },
    },
```
I guess, if it was working with 1.2, it's a v4 tag 🤔

**Comment by romgere** [comment]
Is see when investigate diff from 1.2 to 1.5 that gtag script is now inject in service constructor, where it was inject directly in index.html in v1.2...
So it means (in my case) that the script is injected very late, only at first usage of `gtag.event` ...

I think this explain why number of event & whatnot dropped recently...

**Comment by romgere** [comment]
Also I used Tag assistant to debug my gtag integration & I font that the `event` method of `gtag` service is not working properly..

According to [documentation](https://developers.google.com/analytics/devguides/collection/gtagjs/events) event should be send like this : 
```js
gtag('event', <action>, {
  'event_category': <category>,
  'event_label': <label>,
  'value': <value>
});
```

So implicitly `gatg` function is using : 
```js
dataLayer.push(['event', <action>, {
  'event_category': <category>,
  'event_label': <label>,
  'value': <value>
}])
```

But in `gtag` service, the `event` function is doing : 
```js
dataLayer.push({
  'event': <action>
  'event_category': <category>,
  'event_label': <label>,
  'value': <value>
})
```

Which (according to the doc) is not the way to send custom event ...

I tried changing `event` function to this : 

```js
event(name, params) {
  this.push('event', name, {...params });
}
```

And I can now see my custom event poping in Tag assistant debugger : 
![image](https://github.com/onehilltech/ember-cli-google/assets/13900970/5f07d47c-b89f-4276-8667-6c0c664ee24e)

**Comment by romgere** [comment]
That make me wondering if the `gtatg` service `event` function has been done for sending custom event ? I'm figuring out that previously I was not using the `gtatg` service, but I was calling directly `gtag` function in my app (aka. I was just using your add-on to inject the script 🤔)

**Comment by romgere** [comment]
Another thing I noticed, is that gtag script was previsouly injected by [packages/ember-cli-google-analytics/index.js](https://github.com/onehilltech/ember-cli-google/compare/%40onehilltech/ember-cli-google-analytics%401.2.0...%40onehilltech/ember-cli-google-analytics%401.5.0#diff-ab5e840f78c0e3cadf1530c16f540f04eb51e9776734b6542bec76062ff3a39b) at app build where now, the script is injected at run time when `gtag`service is first used.

I think this change can make a huge difference, given, is the consuming app is not using the `gtag` service, script won't be injected in app 🤔

**Comment by romgere** [comment]
I fixed issue on my side, so from my POV this can be closed, but I let you closing this issue given there may be some action you want to take regarding what was discussed here.
Thx !
